#!/usr/bin/env bash
#transfers a file from our client to a server

pathfile=$1
ip=$2
username=$3

if [[ $# -lt 3 ]]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [[ $# -eq 3 ]]
then
    scp -o StrictHostKeyChecking=no "$pathfile" "$username@$ip":~/
else
    pathssh=$4
    scp -i "$pathssh" -o StrictHostKeyChecking=no "$pathfile" "$username@$ip":~/
fi
