#!/usr/bin/env bash
#Replace a line with multiple lines with sed

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Holberton School" > ~/index.html
cp ~/index.html /var/www/html/

sed -i '/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com permanent;' /etc/ng\
inx/sites-available/default

sudo service nginx restart

