#!/usr/bin/env bash
#Replace a line with multiple lines with sed

apt-get update -y
apt-get install nginx -y

echo "Holberton School" > ~/index.html
cp ~/index.html /var/www/html/

sed -i '/server_name _;/ a\\\trewrite ^/redirect_me https://youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
