#!/usr/bin/env bash
#Not found page 404

apt-get update -y
apt-get install nginx -y

echo "Holberton School" > ~/index.html
cp ~/index.html /var/www/html/

REDI="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}"
sed -i "/server_name _;/ a\\$REDI" /etc/nginx/sites-available/default

ERROR="terror_page {\n\t\treturn 404 /404.html;\n\t}"
sed -i "/redirect_me/ a\\$ERROR" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > ~/404.html
cp ~/404.html /var/www/html/

service nginx restart
