#!/usr/bin/env bash
# installs nginx

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i "/server_name _;/ a\\\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com;\n\t}" /etc/nginx/sites-available/default
sed -i "/server_name _;/ a\\\terror_page 404 /404.html;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
service nginx restart
