#!/usr/bin/env bash
#Double the number of webservers

apt-get update -y
apt-get install nginx -y

echo "Holberton School" > ~/index.html
echo "Ceci n'est pas une page" > ~/404.html

sudo mv ~/404.html /var/www/html/
sudo mv ~/index.html /var/www/html/

config="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name 35.196.133.220;
	rewrite ^/redirect_me google.com permanent;
	add_header X-Served-By $HOSTNAME;
	location /redirect_me {
		return 301 https://edhernautica.tech;
	}
	error_page 404 /custom_404.html;
}"

echo "$config" > ~/config
sudo mkdir -p /etc/nginx/sites-enabled
sudo mv ~/default /etc/nginx/sites-enabled/default
sudo service nginx restart
