#!/usr/bin/env bash
#Double the number of webservers

apt-get update -y
apt-get install haproxy -y

config="frontend main
		 bind *:80
		 mode http
		 default_backend web-server
backend web-server
		balance roundrobin
                server 2229-web-01 34.73.181.230:80 check
                server 2229-web-02 35.196.133.220:80 check
"
echo "$config" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy restart
