#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes: 0 to 12 hours and 1 to 59 min

i=0; j=1
while [ $i -le 12 ]
do
	echo Hour: $i

	j=1
	while [ $j -le 59 ]
	do
		echo $j
		(( j++ ))
	done
	(( i++ ))
done
