#!/usr/bin/env bash
#display content of current directory in a list format - Where only the part of the name after the first dash is displayed (Do not display hidden files)

for file in *
do
	echo "$file" | cut -f 2 -d '-'
done
